name: Deploy to S3

on:
  push:
    branches:
      - main  # 设置为你想要触发上传的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: 'ap-northeast-1'  # 替换为你的AWS区域
          bucket: ouyang.net  # 设置你的 S3 bucket 名字
          bucket-prefix: ''  # 根据需要设置前缀
          local-dir: 'C:\Users\lucyo\OneDrive\文档\GitHub\ouyang0816_1\ouyang0816_1'  # 替换为你构建的本地文件夹路径
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
